version: "3.9"

services:

  nginx:
    image: nginx:alpine
    container_name: prod-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - micro-net

  frontend:
    build: ../../frontend
    container_name: prod-frontend
    networks:
      - micro-net

  backend:
    build: ../../backend
    container_name: prod-backend
    env_file:
      - ../../.env
    networks:
      - micro-net

  db:
    image: postgres:14
    container_name: prod-db
    env_file:
      - ../../database/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - micro-net

volumes:
  db-data:

networks:
  micro-net:
